#include "Disassembler.h"
#include <iomanip>
#include <cmath>
#include <algorithm>

namespace lua_deobfuscator {

Disassembler::Disassembler(const LuaChunk& chunk) : chunk(chunk), indent_level(0), func_counter(0) {}

std::string Disassembler::disassemble(const std::string& closure_filter, bool include_children) {
    output.str("");
    output.clear();
    indent_level = 0;
    func_counter = 0;

    output << "; --[=========[ Lua assembler file generated by LuaDeobfuscator C++" << std::endl;

    // For now, only support full disassembly as filter logic is complex to port
    disassemble_prototype(chunk.main, -1, include_children);

    output << "; ]=========]" << std::endl;
    return output.str();
}

void Disassembler::emit(const std::string& line) {
    for (int i = 0; i < indent_level; ++i) output << "\t";
    output << line << std::endl;
}

void Disassembler::disassemble_prototype(std::shared_ptr<Prototype> proto, int func_num, bool include_children, const std::string& parent_source) {
    bool is_main = (func_num == -1);
    if (is_main) {
        output << "; " << proto->upvalues.size() << " upvalues, " << proto->locvars.size() << " locals, "
               << proto->constants.size() << " constants, " << proto->protos.size() << " funcs" << std::endl;
    } else {
        std::string func_name = "F" + std::to_string(func_num);
        emit(".func " + func_name + " ; " + std::to_string(proto->upvalues.size()) + " upvalues, "
             + std::to_string(proto->locvars.size()) + " locals, " + std::to_string(proto->constants.size())
             + " constants, " + std::to_string(proto->protos.size()) + " funcs");
        indent_level++;
    }

    std::string source = proto->source.empty() ? parent_source : proto->source;
    if (!source.empty()) emit(".source \"" + source + "\"");

    emit(".linedefined " + std::to_string(proto->line_defined));
    emit(".lastlinedefined " + std::to_string(proto->last_line_defined));
    emit(".numparams " + std::to_string(proto->num_params));
    emit(".is_vararg " + std::to_string(proto->is_vararg));
    emit(".maxstacksize " + std::to_string(proto->max_stack_size));
    emit();

    for (size_t i = 0; i < proto->upvalues.size(); ++i) {
        const auto& u = proto->upvalues[i];
        std::string name = u.name.empty() ? ("u" + std::to_string(i)) : u.name;
        if (u.instack) emit(".upval v" + std::to_string(u.idx) + " \"" + name + "\" ; u" + std::to_string(i));
        else emit(".upval u" + std::to_string(u.idx) + " \"" + name + "\" ; u" + std::to_string(i));
    }
    if (!proto->upvalues.empty()) emit();

    std::set<int> jump_targets = collect_jump_targets(proto);
    int closure_offset = func_counter;

    for (size_t pc = 0; pc < proto->code.size(); ++pc) {
        // Local starts at this pc
        for (size_t i = 0; i < proto->locvars.size(); ++i) {
            if (proto->locvars[i].startpc == static_cast<int>(pc)) {
                emit(".local v" + std::to_string(i) + " \"" + proto->locvars[i].varname + "\"");
            }
        }

        if (jump_targets.count(pc)) emit(":goto_" + std::to_string(pc));

        if (pc < proto->lineinfo.size() && proto->lineinfo[pc] > 0) {
            // simplified: always emit line for now or track last_line
            emit(".line " + std::to_string(proto->lineinfo[pc]));
        }

        emit(format_instruction(proto->code[pc], proto, pc, closure_offset, jump_targets));
        emit();
    }

    for (size_t i = 0; i < proto->locvars.size(); ++i) {
        emit(".end local v" + std::to_string(i) + " \"" + proto->locvars[i].varname + "\"");
    }
    if (!proto->locvars.empty()) emit();

    if (include_children && !proto->protos.empty()) {
        int n = proto->protos.size();
        int offset = func_counter;
        func_counter += n;
        for (int i = 0; i < n; ++i) {
            disassemble_prototype(proto->protos[i], offset + i, include_children, source);
        }
    }

    if (!is_main) {
        indent_level--;
        emit(".end ; F" + std::to_string(func_num));
        emit();
    }
}

std::set<int> Disassembler::collect_jump_targets(std::shared_ptr<Prototype> proto) {
    std::set<int> targets;
    for (size_t pc = 0; pc < proto->code.size(); ++pc) {
        Opcode op = static_cast<Opcode>(proto->code[pc].opcode);
        if (op == Opcode::JMP || op == Opcode::FORLOOP || op == Opcode::FORPREP || op == Opcode::TFORLOOP) {
            targets.insert(pc + proto->code[pc].sbx + 1);
        }
    }
    return targets;
}

std::string Disassembler::format_constant(const LuaConstant& c) {
    return c.to_string();
}

std::string Disassembler::format_instruction(const Instruction& instr, std::shared_ptr<Prototype> proto, int pc, int closure_offset, const std::set<int>& jump_targets) {
    Opcode op = static_cast<Opcode>(instr.opcode);
    std::string name = instr.opcode_name;

    auto rk = [&](int val) {
        if (ISK(val)) {
            int k_idx = INDEXK(val);
            if (k_idx < (int)proto->constants.size()) return format_constant(proto->constants[k_idx]);
            return std::string("K") + std::to_string(k_idx);
        }
        return std::string("v") + std::to_string(val);
    };

    auto jmp_label = [&](int sbx) {
        int target = pc + sbx + 1;
        std::string arrow = (sbx >= 0) ? "↓" : "↑";
        return std::string(":goto_") + std::to_string(target) + "  ; " + (sbx >= 0 ? "+" : "") + std::to_string(sbx) + " " + arrow;
    };

    switch (op) {
        case Opcode::MOVE: return "MOVE v" + std::to_string(instr.a) + " v" + std::to_string(instr.b);
        case Opcode::LOADK: return "LOADK v" + std::to_string(instr.a) + " " + (instr.bx < (int)proto->constants.size() ? format_constant(proto->constants[instr.bx]) : "K" + std::to_string(instr.bx));
        case Opcode::LOADKX: return "LOADKX v" + std::to_string(instr.a);
        case Opcode::LOADBOOL: return "LOADBOOL v" + std::to_string(instr.a) + " " + std::to_string(instr.b) + " " + std::to_string(instr.c);
        case Opcode::LOADNIL: return "LOADNIL v" + std::to_string(instr.a) + (instr.b > 0 ? ("..v" + std::to_string(instr.a + instr.b)) : "");
        case Opcode::GETUPVAL: return "GETUPVAL v" + std::to_string(instr.a) + " u" + std::to_string(instr.b);
        case Opcode::GETTABUP: return "GETTABUP v" + std::to_string(instr.a) + " u" + std::to_string(instr.b) + " " + rk(instr.c);
        case Opcode::GETTABLE: return "GETTABLE v" + std::to_string(instr.a) + " v" + std::to_string(instr.b) + " " + rk(instr.c);
        case Opcode::SETTABUP: return "SETTABUP u" + std::to_string(instr.a) + " " + rk(instr.b) + " " + rk(instr.c);
        case Opcode::SETUPVAL: return "SETUPVAL v" + std::to_string(instr.a) + " u" + std::to_string(instr.b);
        case Opcode::SETTABLE: return "SETTABLE v" + std::to_string(instr.a) + " " + rk(instr.b) + " " + rk(instr.c);
        case Opcode::NEWTABLE: return "NEWTABLE v" + std::to_string(instr.a) + " " + std::to_string(instr.b) + " " + std::to_string(instr.c);
        case Opcode::SELF: return "SELF v" + std::to_string(instr.a) + " v" + std::to_string(instr.b) + " " + rk(instr.c);
        case Opcode::ADD:
        case Opcode::SUB:
        case Opcode::MUL:
        case Opcode::DIV:
        case Opcode::MOD:
        case Opcode::POW:
        case Opcode::IDIV:
        case Opcode::BAND:
        case Opcode::BOR:
        case Opcode::BXOR:
        case Opcode::SHL:
        case Opcode::SHR:
            return name + " v" + std::to_string(instr.a) + " " + rk(instr.b) + " " + rk(instr.c);
        case Opcode::UNM:
        case Opcode::BNOT:
        case Opcode::NOT:
        case Opcode::LEN:
            return name + " v" + std::to_string(instr.a) + " v" + std::to_string(instr.b);
        case Opcode::CONCAT: return "CONCAT v" + std::to_string(instr.a) + " v" + std::to_string(instr.b) + " v" + std::to_string(instr.c);
        case Opcode::JMP: return "JMP " + (instr.a != 0 ? std::to_string(instr.a) + " " : "") + jmp_label(instr.sbx);
        case Opcode::EQ:
        case Opcode::LT:
        case Opcode::LE:
        case Opcode::NEQ:
        case Opcode::GE:
        case Opcode::GT:
            return name + " " + std::to_string(instr.a) + " " + rk(instr.b) + " " + rk(instr.c);
        case Opcode::TEST: return "TEST v" + std::to_string(instr.a) + " " + std::to_string(instr.c);
        case Opcode::TESTSET: return "TESTSET v" + std::to_string(instr.a) + " v" + std::to_string(instr.b) + " " + std::to_string(instr.c);
        case Opcode::CALL: return "CALL v" + std::to_string(instr.a) + (instr.b != 1 ? ("..v" + std::to_string(instr.a + instr.b - 1)) : "") + (instr.c > 1 ? (" v" + std::to_string(instr.a) + "..v" + std::to_string(instr.a + instr.c - 2)) : "");
        case Opcode::RETURN: return "RETURN " + (instr.b > 1 ? ("v" + std::to_string(instr.a) + (instr.b > 2 ? ("..v" + std::to_string(instr.a + instr.b - 2)) : "")) : "");
        case Opcode::FORLOOP: return "FORLOOP v" + std::to_string(instr.a) + " " + jmp_label(instr.sbx);
        case Opcode::FORPREP: return "FORPREP v" + std::to_string(instr.a) + " " + jmp_label(instr.sbx);
        case Opcode::TFORLOOP: return "TFORLOOP v" + std::to_string(instr.a) + " " + jmp_label(instr.sbx);
        case Opcode::CLOSURE: return "CLOSURE v" + std::to_string(instr.a) + " F" + std::to_string(closure_offset + instr.bx);
        case Opcode::VARARG: return "VARARG " + (instr.b > 1 ? ("v" + std::to_string(instr.a) + "..v" + std::to_string(instr.a + instr.b - 2)) : "");
        default: return name + " " + std::to_string(instr.a) + " " + std::to_string(instr.b) + " " + std::to_string(instr.c);
    }
}

} // namespace lua_deobfuscator
